---
- name: Configure all hosts
  hosts: home
  roles:
    - role: system
    - role: fish

- name: Configure servers hosts
  hosts: servers
  roles:
    - { role: geerlingguy.security, become: true }
    - { role: chriswayg.msmtp-mailer, become: true }
    - role: unatended_upgrades

- name: Configure aspire server
  hosts: aspire
  roles:
    - role: dropbear
    - role: samba
    - role: nfs
    - role: docker
    - role: media-server
