---
- name: Get render group info
  ansible.builtin.getent:
    database: group
    key: render

- name: Set a variable for render gid
  ansible.builtin.set_fact:
    render_gid: "{{ ansible_facts.getent_group.render[1] }}"

- name: Create docker folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ docker.infra }}"
    - "{{ docker.volumes }}"

- name: Create all docker infrastructure related folders
  ansible.builtin.file:
    path: "{{ docker.infra }}/{{ item.path }}"
    state: directory
    mode: "0755"

  with_community.general.filetree: "../templates"
  when: item.state == 'directory'

- name: Copy all docker files
  ansible.builtin.template:
    src: "{{ item.path }}"
    dest: "{{ docker.infra }}/{{ item.path | replace('.j2', '') }}"
    mode: "0644"
  with_community.general.filetree: "../templates"
  when: item.state == 'file'

- name: Start the docker services
  community.docker.docker_compose_v2:
    build: always
    project_src: "{{ docker.infra }}"
    pull: always
    remove_orphans: true
    remove_images: all
    remove_volumes: true
